# Generated by Django 5.2 on 2025-05-24 17:27

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("likes", "0001_initial"),
        ("posts", "0005_post_comments_number"),
    ]

    operations = [
        migrations.AlterField(
            model_name="like",
            name="to_post",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="like_to_post",
                to="posts.post",
            ),
        ),
    ]
