version: "3.9"


services:
  web:
    build: .
    command: > 
      sh -c "python manage.py migrate && 
      python manage.py runserver 0.0.0.0:8000"

    volumes :
      - .:/app
      - static:/app/static
      - sqlite_data:/app/data
    ports :
      - "8000:8000"
    # env_file:
    #   - .env
    environment:
      DJANGO_DB_PATH: /app/data/db.sqlite3  
      REDIS_HOST: redis                   
      REDIS_PORT: 6379  

    depends_on : 
      - redis 

    container_name : django_web

    restart : always
    networks : 
      - backend 


  redis : 
    container_name : redis
    image : redis:8   
    volumes : 
      - redis_data:/data
    networks : 
      - backend 


volumes : 
  redis_data: 
  static : 
  sqlite_data: 



networks: 
  backend: 


