# Generated by Django 5.2.4 on 2025-08-17 18:46

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Chat",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, help_text="Дата и время создания чата"
                    ),
                ),
                (
                    "from_user",
                    models.ForeignKey(
                        blank=True,
                        help_text="Пользователь, который инициировал чат",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="chat_who_created",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "to_user",
                    models.ForeignKey(
                        blank=True,
                        help_text="Пользователь, который участвует в чате",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="chat_who_accepted",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Чат",
                "verbose_name_plural": "Чаты",
                "unique_together": {("to_user", "from_user")},
            },
        ),
        migrations.CreateModel(
            name="Message",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "text",
                    models.TextField(
                        help_text="Текст сообщения (до 1000 символов)", max_length=1000
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, help_text="Дата и время отправки сообщения"
                    ),
                ),
                (
                    "from_who",
                    models.ForeignKey(
                        blank=True,
                        help_text="Автор сообщения",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="message_owner",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "to_chat",
                    models.ForeignKey(
                        blank=True,
                        help_text="Чат, в котором отправлено сообщение",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="message_to_chat",
                        to="chat.chat",
                    ),
                ),
            ],
            options={
                "verbose_name": "Сообщение",
                "verbose_name_plural": "Сообщения",
            },
        ),
        migrations.CreateModel(
            name="ChatLastSeen",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "last_seen",
                    models.DateTimeField(
                        auto_now=True,
                        help_text="Дата и время последнего прочтения чата пользователем",
                    ),
                ),
                (
                    "chat",
                    models.ForeignKey(
                        help_text="Чат, к которому относится отметка",
                        on_delete=django.db.models.deletion.CASCADE,
                        to="chat.chat",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        help_text="Пользователь, который читал чат",
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Последнее прочтение чата",
                "verbose_name_plural": "Последние прочтения чатов",
                "unique_together": {("chat", "user")},
            },
        ),
    ]
