# Generated by Django 5.2.4 on 2025-08-16 22:23

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("chat", "0001_initial"),
        ("users", "0006_preregistration"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="chat",
            options={"verbose_name": "Чат", "verbose_name_plural": "Чаты"},
        ),
        migrations.AlterModelOptions(
            name="message",
            options={"verbose_name": "Сообщение", "verbose_name_plural": "Сообщения"},
        ),
        migrations.AlterField(
            model_name="chat",
            name="created_at",
            field=models.DateTimeField(
                auto_now_add=True, help_text="Дата и время создания чата"
            ),
        ),
        migrations.AlterField(
            model_name="chat",
            name="from_user",
            field=models.ForeignKey(
                blank=True,
                help_text="Пользователь, который инициировал чат",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="chat_who_created",
                to="users.user",
            ),
        ),
        migrations.AlterField(
            model_name="chat",
            name="to_user",
            field=models.ForeignKey(
                blank=True,
                help_text="Пользователь, который участвует в чате",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="chat_who_accepted",
                to="users.user",
            ),
        ),
        migrations.AlterField(
            model_name="message",
            name="created_at",
            field=models.DateTimeField(
                auto_now_add=True, help_text="Дата и время отправки сообщения"
            ),
        ),
        migrations.AlterField(
            model_name="message",
            name="from_who",
            field=models.ForeignKey(
                blank=True,
                help_text="Автор сообщения",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="message_owner",
                to="users.user",
            ),
        ),
        migrations.AlterField(
            model_name="message",
            name="text",
            field=models.TextField(
                help_text="Текст сообщения (до 1000 символов)", max_length=1000
            ),
        ),
        migrations.AlterField(
            model_name="message",
            name="to_chat",
            field=models.ForeignKey(
                blank=True,
                help_text="Чат, в котором отправлено сообщение",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="message_to_chat",
                to="chat.chat",
            ),
        ),
        migrations.AlterUniqueTogether(
            name="chat",
            unique_together={("to_user", "from_user")},
        ),
        migrations.CreateModel(
            name="ChatLastSeen",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "last_seen",
                    models.DateTimeField(
                        auto_now=True,
                        help_text="Дата и время последнего прочтения чата пользователем",
                    ),
                ),
                (
                    "chat",
                    models.ForeignKey(
                        help_text="Чат, к которому относится отметка",
                        on_delete=django.db.models.deletion.CASCADE,
                        to="chat.chat",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        help_text="Пользователь, который читал чат",
                        on_delete=django.db.models.deletion.CASCADE,
                        to="users.user",
                    ),
                ),
            ],
            options={
                "verbose_name": "Последнее прочтение чата",
                "verbose_name_plural": "Последние прочтения чатов",
                "unique_together": {("chat", "user")},
            },
        ),
    ]
