# Generated by Django 5.2 on 2025-05-14 14:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("posts", "0002_remove_post_owner_post_post_id_alter_post_id_and_more"),
    ]

    operations = [
        migrations.RenameField(
            model_name="post",
            old_name="id",
            new_name="owner_id",
        ),
    ]
