# Generated by Django 5.2 on 2025-05-23 11:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("posts", "0003_rename_id_post_owner_id"),
    ]

    operations = [
        migrations.RenameField(
            model_name="post",
            old_name="post_id",
            new_name="id",
        ),
        migrations.RenameField(
            model_name="post",
            old_name="owner_id",
            new_name="owner",
        ),
    ]
