# Generated by Django 5.2 on 2025-05-24 17:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("posts", "0004_rename_post_id_post_id_rename_owner_id_post_owner"),
    ]

    operations = [
        migrations.AddField(
            model_name="post",
            name="comments_number",
            field=models.IntegerField(default=0),
        ),
    ]
