# Generated by Django 5.2 on 2025-05-17 18:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0005_friendship_user_friends"),
    ]

    operations = [
        migrations.CreateModel(
            name="PreRegistration",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("email", models.EmailField(max_length=100)),
                ("name", models.CharField(max_length=30, verbose_name="Имя")),
                ("code", models.IntegerField()),
                ("username", models.CharField(max_length=30, verbose_name="Юз")),
                (
                    "avatar",
                    models.ImageField(
                        blank=True, null=True, upload_to="photo", verbose_name="Ава"
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
